# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/data_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources.logo_rc


class Ui_data_window(object):
    def setupUi(self, data_window):
        data_window.setObjectName("data_window")
        data_window.resize(1104, 859)
        font = QtGui.QFont()
        font.setFamily("Romantic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        data_window.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(data_window)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 470, 491, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.form_data = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.form_data.setContentsMargins(0, 0, 0, 0)
        self.form_data.setObjectName("form_data")
        self.password = QtWidgets.QLabel(self.gridLayoutWidget)
        self.password.setObjectName("password")
        self.form_data.addWidget(self.password, 3, 0, 1, 1)
        self.password_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password_input.setObjectName("password_input")
        self.form_data.addWidget(self.password_input, 3, 2, 1, 1)
        self.email = QtWidgets.QLabel(self.gridLayoutWidget)
        self.email.setObjectName("email")
        self.form_data.addWidget(self.email, 0, 0, 1, 1)
        self.email_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.email_input.setObjectName("email_input")
        self.form_data.addWidget(self.email_input, 0, 2, 1, 1)
        self.name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.form_data.addWidget(self.name, 4, 0, 1, 1)
        self.asu_id_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.asu_id_input.setObjectName("asu_id_input")
        self.form_data.addWidget(self.asu_id_input, 1, 2, 1, 1)
        self.uel_id = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uel_id.setObjectName("uel_id")
        self.form_data.addWidget(self.uel_id, 2, 0, 1, 1)
        self.asu_id = QtWidgets.QLabel(self.gridLayoutWidget)
        self.asu_id.setObjectName("asu_id")
        self.form_data.addWidget(self.asu_id, 1, 0, 1, 1)
        self.name_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name_input.setObjectName("name_input")
        self.form_data.addWidget(self.name_input, 4, 2, 1, 1)
        self.uel_id_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.uel_id_input.setObjectName("uel_id_input")
        self.form_data.addWidget(self.uel_id_input, 2, 2, 1, 1)
        self.get_portfolio = QtWidgets.QPushButton(data_window)
        self.get_portfolio.setGeometry(QtCore.QRect(760, 550, 251, 71))
        self.get_portfolio.setObjectName("get_portfolio")
        self.get_portfolio.clicked.connect(self.get_portfolio_data)
        self.frame = QtWidgets.QFrame(data_window)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1121, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.banner_data = QtWidgets.QLabel(self.frame)
        self.banner_data.setGeometry(QtCore.QRect(-30, -60, 1211, 411))
        self.banner_data.setStyleSheet("image: url(:/images/slide1.jpg);")
        self.banner_data.setLineWidth(1)
        self.banner_data.setText("")
        self.banner_data.setObjectName("banner_data")
        self.retranslateUi(data_window)
        QtCore.QMetaObject.connectSlotsByName(data_window)

    def retranslateUi(self, data_window):
        _translate = QtCore.QCoreApplication.translate
        data_window.setWindowTitle(_translate("data_window", "Form"))
        self.password.setText(_translate("data_window", "Password: "))
        self.email.setText(_translate("data_window", "Email:"))
        self.name.setText(_translate("data_window", "Name:"))
        self.uel_id.setText(_translate("data_window", "UEL ID:"))
        self.asu_id.setText(_translate("data_window", "ASU ID:"))
        self.get_portfolio.setText(_translate("data_window", "Get Portfolio"))

    def get_portfolio_data(self, e):
        print("getting portfolio...")
        name = self.name_input.text()
        password = self.password_input.text()
        email = self.email_input.text()
        uel_id = self.uel_id_input.text()
        asu_id = self.uel_id_input.text()
        self.name_input.clear()
        self.email_input.clear()
        self.password_input.clear()
        self.asu_id_input.clear()
        self.uel_id_input.clear()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    with open("resources/css/styles.css") as f:
        styles = f.read()
    app.setStyleSheet(styles)
    data_window = QtWidgets.QWidget()
    ui = Ui_data_window()
    ui.setupUi(data_window)
    data_window.show()
    sys.exit(app.exec_())
